version: '2'
  
services:
  log-generator:
    build:
      context: ../log-generator/
      dockerfile: Dockerfile
    container_name: log-generator
    environment:
      - LOG_FILE_DIR=./
    networks:
      - kafka

  analysis-module:
    build:
      context: ../log-analysis-module/
      dockerfile: Dockerfile
    container_name: analysis-module
    environment:
      - ES_SERVER=http://elastic:9200
    networks:
      - kafka
      - elk

networks:
  test:
    external:
      name: kafka-docker-compose_test